; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs
lib_deps = 
	esp32async/AsyncTCP@^3.4.10
	esp32async/ESPAsyncWebServer@^3.10.0
	knolleary/PubSubClient@^2.8
	knolleary/PubSubClient
	bblanchon/ArduinoJson
	marvinroger/AsyncMqttClient
	hideakitai/MPU9250@^0.4.8
	bolderflight/Bolder Flight Systems MPU9250@^1.0.2
